---
- name: Playbook for configuring nagios server
  hosts: all
  
  tasks:
  
  - name: download binaries to server
    get_url: 
      url: https://github.com/baba-dude/Nagios/blob/master/xi-5.4.11.tar.gz
      dest: /tmp/
      mode: 0755
      
      
  #- name: download file
   # shell: wget "https://github.com/baba-dude/Nagios/blob/master/xi-5.4.11.tar.gz"

      
  - name: Extract xi-5.4.11.tar.gz to remote host /tmp directory.
    unarchive:
      src: /tmp/xi-5.4.11.tar.gz
      dest: /tmp/
      remote_src: yes
 
  - name: Run script fullinstall
    command: ./fullinstall -n
    args:
      chdir: /tmp/nagiosxi

  - name: Create nagiosadmin user password
    shell: htpasswd -cb /usr/local/nagiosxi/etc/htpasswd.users nagiosadmin nagios

